### ISSUE TITLE
pagefunnel not visible

### ISSUE THREAD

**Issue by asche76** [in2code-de/powermail#1009]
in T3 12.4.x / powermail 12.3.0 the pagefunnel is not visible. marketing static template is included.
is this configurable somewhere?

![image](https://github.com/in2code-de/powermail/assets/47745128/959ed97a-3177-4e2d-9262-4404ac458bb8)

**Comment by dennismetz** [comment]
I have the same problem.
When I call up the URL for marketing directly, i.e. website.tld/contact?type=1540053358, I get a JSON error:

No TypoScript configuration found. Admin, have you included the static template "Main"?

**Comment by dennismetz** [comment]
Is there an update on this yet?

**Comment by mschwemer** [comment]
Solved with 5e06c9b18130625cc2a147e923f086d3c4c164ba
