### ISSUE TITLE
ExtensionService::getPluginNameByAction() must be of the type string, null given

### ISSUE THREAD

**Issue by devxpoint** [in2code-de/powermail#1010]
Hello, I use TYPO3 10 with powermail 8.4.2
Created a simple form on a news detail page and get an error after submit:
Argument 1 passed to TYPO3\CMS\Extbase\Service\ExtensionService::getPluginNameByAction() must be of the type string, null given,
called in /.../typo3/sysext/extbase/Classes/Mvc/Web/Routing/UriBuilder.php on line 611
Put it on a single page  -> same error

I have other forms on the same website, these are working. :)

**Comment by mschwemer** [comment]
Can you provide more information, how to reproduce it?

**Comment by mschwemer** [comment]
TYPO3 v10 is EELTS ... so closing it. 

You can get paid support via https://www.in2code.de/en/contact/, if you need it solved for that version
