### ISSUE TITLE
PHP Warning: Undefined variable $isSavingOfMailAllowed

### ISSUE THREAD

**Issue by wolfgang007** [in2code-de/powermail#1012]
**Bug description**
Hi Guys,
after I update from PHP 7.4 to 8.2 i got the following error, if I clicked on the OptIn-link in mail:

"PHP Warning: Undefined variable $isSavingOfMailAllowed in /html/typo3-staging/typo3conf/ext/powermail/Classes/Controller/FormController.php line 225"

Can anyone help me? Is there a quick bugfix?
With PHP 7.4 it works

**Environment:**
TYPO3 version: 11.5.35
PHP version: 8.2.*
Extension version: 10.8.0

![screenshot](https://github.com/in2code-de/powermail/assets/17067590/d12abae5-3878-4ef7-abc9-6f752430cbe3)

**Comment by medarob** [comment]
I just got the same problem!

TYPO3 11.5.37
powermail 10.8.1
PHP 8.2.19


It works with PHP 7.4.

**Comment by mschwemer** [comment]
Solved with version 10.8.2
