### ISSUE TITLE
PHP Warning: Array to string conversion -- on submit powermail form without captcha checked.

### ISSUE THREAD

**Issue by Pravin0711** [in2code-de/powermail#1016]
Hello,

I am using typo3 11.5 and powermail 10.8.0. Also, i am using `powermailcaptcha` extension for google recaptcha.

Now, my issue is when i submit form without captcha feilds i get below error message. if i submit form with captcha then it's work fine.

`PHP Warning: Array to string conversion in "../../typo3_src-11.5.36/vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/AbstractNode.php line 73"`

Please help me. where i am wrong.

**Comment by mschwemer** [comment]
This is an issue with powermailcaptcha. Please report it there. Thx
