### ISSUE TITLE
Indexes for form and feuser in the tx_powermail_domain_model_mail table

### ISSUE THREAD

**Issue by tobiasschaeferptb** [in2code-de/powermail#1017]
Hello,

we had performance issues with an installation with thousands of entries in tx_powermail_domain_model_mail table.
The problem occured in the backend on pages with powermail plugins and in the frontend on pages with the powermail frontend plugin.
We could solve the issue by adding 2 indexes for the columns form and feuser in the tx_powermail_domain_model_mail table.
ext_tables.sql, line 207, change from:
`KEY language (l10n_parent,sys_language_uid)`
to
```
KEY language (l10n_parent,sys_language_uid),
KEY form (form),
KEY feuser (feuser)
```
Would it be possible to add these two indexes?

Best regards,
Tobias Schaefer

**Comment by mschwemer** [comment]
Included in 12.3.4
