### ISSUE TITLE
TypeError in PowermailPermissionUpdater

### ISSUE THREAD

**Issue by svewap** [in2code-de/powermail#1019]
On many systems, this update task fails because the argument $row['explicit_allowdeny'] has the value null.

![ksnip_20240501-003038](https://github.com/in2code-de/powermail/assets/1734738/8cf7f28a-f3c8-4f37-a366-a01fd7cc19a6)

**Comment by mschwemer** [comment]
@svewap I have got an idea howto fix it, but I am not able to reproduce the exception. 

Can you provide your table definition of  `be_groups` and the database rows of the table `be_groups`, of an instance, which has this error?

TIA

**Comment by mschwemer** [comment]
Solved with PR in2code-de/powermail#1074
