### ISSUE TITLE
Error on form submission with powermail exactly 12.3.2

### ISSUE THREAD

**Issue by rupasix** [in2code-de/powermail#1024]
Typo3 - 12.4.4
Powermail: 12.3.2
PHP: Tested 8.2 and 8.3
Typo3 test instance without additional configurations - all is default.

Version 12.3.2 breaks form submission. It worked with 12.3.1
`Exception while property mapping at property path "": It is not allowed to map property "answers". You need to use $propertyMappingConfiguration->allowProperties('answers') to enable mapping of this property.`
![image](https://github.com/in2code-de/powermail/assets/9860558/aa1ef142-e5ff-429c-9bd8-1864a345d13c)

How to reproduce:
Install powermail, 
Create form+page+textfield mail+submit, 
Create plugin with sender and thanks configured.
Submit form in frontend

**Comment by MKupi** [comment]
I can confirm this issue after an update from TYPO3 9 to 12 and in this context with an update to powermail 12.3.2.
After downgrading to powermail 12.3.1 form submission succeeded.

**Comment by BokuNoMaxi** [comment]
we got that issue too today with exact this version.

**Comment by abvdveen** [comment]
We too, exact same version. Proposed fix by @Runik51ua gives the same error.

**Comment by tntrpsw** [comment]
I can reproduce the error using TYPO3 12.4.14 and powermail 12.3.2:

> Exception while property mapping at property path "": It is not allowed to map property "answers". You need to use $propertyMappingConfiguration->allowProperties('answers') to enable mapping of this property.

**Comment by Teisi** [comment]
Now i have this issue too.
TYPO3 12.4.14
powermail 12.3.2

Nothing special: extensions installed -> created plugin on a page -> create a form with fields "email" and "send". 
Filled out receiver.name and receiver.email and receiver.subject in the plugin settings. All other options are default.

With powermail 12.3.1 this works fine.

**Comment by fishgit** [comment]
Confirmed here. Downgrading to 12.3.1 works. 

Another issue is: With 12.3.2 and redirect to answer page option set the error message does not appear but no email is sent. Downgrade to 12.3.1 solves this, too.

**Comment by wrock** [comment]
Confirmed here too, 12.3.1 works. 12.3.2 throws the error.

**Comment by vnc-jboe** [comment]
The error occured after updating from 12.3.1 to 12.3.2

The new function initializeCheckCreateAction calls the function reformatParamsForAction in the FormController at line 217. At this point the function reformatParamsForAction does not work correctly and misses to set the propertyMappingConfiguration correctly.

By removing this call in an XClass of FormController, powermail throws no error.

Is the reformatParamsForAction function call really needed?

**Comment by mschwemer** [comment]
Thx @Runik51ua for the PR. 

The fix will be included in the next release.

**Comment by ingeniumdesign** [comment]
same here, downgrade on 12.3.1 works.

**Comment by dennismetz** [comment]
@mschwemer when is the next release planned?

**Comment by linawolf** [comment]
same here, downgrade on 12.3.1 works.

**Comment by w010** [comment]
Same situation, works after downgrade to 12.3.1

**Comment by kszymukowicz** [comment]
True.

**Comment by MohsinQK** [comment]
Same, works after downgrade to 12.3.1
