### ISSUE TITLE
Issue when submitting multiple selection check box in powermail 12.3.1

### ISSUE THREAD

**Issue by pitssavinmb** [in2code-de/powermail#1027]
The form field "tx_powermail_pi1[field][eintritt][][]" is invalid. Reason: "[]" used not as last argument, but somewhere in the middle (like foo[][bar]).
![Capture](https://github.com/in2code-de/powermail/assets/164833667/ecd28c0d-6a77-48d1-971f-e0e844aa2a11)

**Comment by hannesbochmann** [comment]
I can confirm this issue, too.

**Comment by mschwemer** [comment]
I cannot reproduce the issue. 

Can you please provide more information? 

Powermail version? 
TYPO3 version? 
php Version? 
Example form definition?


TIA

**Comment by hannesbochmann** [comment]
powermail: 12.3.1 (furthermore powermail_cond 11.2.2 is installed)
TYPO3: 12.4.15
PHP: 8.2.17

Any form with a checkbox element will produce this error. This seems to happen since the last TYPO3 update.

**Comment by hannesbochmann** [comment]
This error happens with TYPO3 12.4.14, too. So it's not because of the latest update. And the error happens with powermail 12.3.2, too as well.

**Comment by hannesbochmann** [comment]
Problem solved! The template Resources/Private/Partials/Form/Field/Check.html was overwritten in our installation and changes weren't taken over. In this case it was the missing multiple="true" attribute.

**Comment by hannesbochmann** [comment]
Just to be more precise. With "changes weren't taken over" I mean the changes in powermail from version 8 to 12.
