### ISSUE TITLE
Exception while property mapping at property path "" when submitting from

### ISSUE THREAD

**Issue by Hasan-Shaker** [in2code-de/powermail#1031]
Hello,
I have this err when i submit any form.
URL : ...?tx_powermail_pi1%5Baction%5D=checkCreate&tx_powermail_pi1%5Bcontroller%5D=Form&cHash=......

###############
Exception while property mapping at property path "": It is not allowed to map property "answers". You need to use $propertyMappingConfiguration->allowProperties('answers') to enable mapping of this property.
###############

TYPO3 V-12
PHP : 8.2
Powermail : 12.3.2

![TYPO3_Exception](https://github.com/in2code-de/powermail/assets/51764849/8e99ca17-c672-4220-b04a-4779f9413a6e)

**Comment by MKupi** [comment]
There's already an issue for this bug: #1024
Solution for now is to switch to powermail 12.3.1

**Comment by Hasan-Shaker** [comment]
OK,
Thanks
#1024
