### ISSUE TITLE
[10.8.x] Accept uppercase chars in frontend form validation for urls

### ISSUE THREAD

**Issue by tobiasschaeferptb** [in2code-de/powermail#1033]
Hello,

The bug that was fixed with this commit https://github.com/in2code-de/powermail/commit/350859c99a97192ea9f1063965f57d7402d3a66f wasn't fixed for the 10.8.x version. Since TYPO3 11.5 is still supported it would be great if the bugfix could be applied for the 10.8.x version too. Thanks.

Best regards,
Tobias Schäfer

**Comment by mschwemer** [comment]
Sorry for the delay. Won't backport it as TYPO3 v11 is already in ELTS.

I recommend to patch it yourself.

If you need it in an official version, you can get paid support via https://www.in2code.de/en/contact/ and we will make a new release for it.
