### ISSUE TITLE
[10.8.1] Error The method "getSorting" is not supported by the repository.

### ISSUE THREAD

**Issue by tobiasschaeferptb** [in2code-de/powermail#1034]
Hello,

After updating from Powermail 10.8.0 to 10.8.1 under TYPO3 11.5.37 I get the error "The method getSorting is not supported by the repository" when I click in the page modul on a page with a powermail plugin. The full error message is:
`Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1233180480: The method "getSorting" is not supported by the repository. | TYPO3\CMS\Extbase\Persistence\Generic\Exception\UnsupportedMethodException thrown in file /typo3/sysext/extbase/Classes/Persistence/Repository.php in line 256.`
Downgrading to 10.8.0 fixes the bug.

Best regards,
Tobias Schäfer

**Comment by mschwemer** [comment]
I close the issue now. 

Since TYPO3 v11 is soonish in ELTS, there will be no fix for that. 

If you are still hit by the issue and need to solve it, you can get payed support via in2code at https://www.in2code.de/en/contact/
