### ISSUE TITLE
Table mapping for be_users and be_groups

### ISSUE THREAD

**Issue by vnc-jboe** [in2code-de/powermail#1036]
The table mapping for be_users and be_groups is not correct.

If you want to set the receiver mails to a specific backend group, it does not work.

I already wrote a fix and made a pull request.

https://github.com/in2code-de/powermail/pull/1035

**Comment by vnc-jboe** [comment]
@mschwemer Could you take care of the fix? 

A client needs this functionality and we would not like to write a patch.

**Comment by mschwemer** [comment]
Thanks for your contribution. Merged your PR,
