### ISSUE TITLE
TCA: marketing_frontend_language configuration

### ISSUE THREAD

**Issue by julianhofmann** [in2code-de/powermail#1057]
In "Check TCA Migrations" there are multiple entries about the obsolete marketing_frontend_language field.

> The TCA field 'marketing_frontend_language' in table 'tx_powermail_domain_model_mail'" defines eval="int". The field has therefore been migrated to the TCA type 'number'. This includes corresponding migration of the "eval" list, as well as obsolete field configurations, such as "max". Please adjust your TCA accordingly.

**Comment by mschwemer** [comment]
Solved with PR #1133

All TCA migrations are green.
