### ISSUE TITLE
TCA: Named keys for items 

### ISSUE THREAD

**Issue by julianhofmann** [in2code-de/powermail#1058]
In "Check TCA Migrations" there are multiple entries about array keys of items.

Examples:

> The TCA field 'validation' of table 'tx_powermail_domain_model_field' uses the legacy way of defining 'items'. Please switch to associated array keys: label, value, icon, group, description.
> The TCA field 'feuser_value' of table 'tx_powermail_domain_model_field' uses the legacy way of defining 'items'. Please switch to associated array keys: label, value, icon, group, description.
> The TCA field 'css' of table 'tx_powermail_domain_model_field' uses the legacy way of defining 'items'. Please switch to associated array keys: label, value, icon, group, description.

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.3/Deprecation-99739-IndexedArrayKeysForTCAItems.html

**Comment by mschwemer** [comment]
Solved with PR #1133
