### ISSUE TITLE
PHP Warning - Redirect (mail empty) - PHP 8.3

### ISSUE THREAD

**Issue by mirkanglanz** [in2code-de/powermail#1060]
Hello, since Version 10.8.1. which fixed the warning "Required argument "mail" is not set for In2code\Powermail\Controller\FormController" new warnings appears now:

[WARNING] request="123456" component="In2code.Powermail.Controller.FormController": Redirect (mail empty) - {"action":"confirmation","controller":"Form"}

[WARNING] request="123456" component="In2code.Powermail.Controller.FormController": Redirect (mail empty) - {"action":"create","controller":"Form"}

TYPO3 11.5.37
Powermail 10.8.1
PHP 8.3

**Comment by mschwemer** [comment]
These warnings are fixed with the latest security releases.
