### ISSUE TITLE
Running Upgrade Wizard "EXT:powermail: Migrate plugin permissions" has exception because of DB field be_groups.explicit_allowdeny

### ISSUE THREAD

**Issue by sypets** [in2code-de/powermail#1062]
` php vendor/bin/typo3 upgrade:run`

```
Running Wizard "EXT:powermail: Migrate plugin permissions"
==========================================================


Uncaught TYPO3 Exception str_replace(): Argument #3 ($subject) must be of type array|string, null given
thrown in file /var/www/dev3.t3.uol.de/vendor/in2code/powermail/Classes/Update/PowermailPermissionUpdater.php
in line 116
```
## version

* powermail: 12.3.5
* TYPO3: 12.4.16

## Reason

**powermail/Classes/Update/PowermailPermissionUpdater.php:** Zeile 116

`$newList = str_replace(array_keys($searchReplace), array_values($searchReplace), $row['explicit_allowdeny']);`

https://github.com/in2code-de/powermail/blob/master/Classes/Update/PowermailPermissionUpdater.php#L116

Some DB-fields are NULL:

`select uid,explicit_allowdeny from be_groups where explicit_allowdeny is NULL;`

## Solution

1. in DB:

`update be_groups set explicit_allowdeny='' where explicit_allowdeny is NULL;`

2. Fix code to handle NULL:

```
- $newList = str_replace(array_keys($searchReplace), array_values($searchReplace), $row['explicit_allowdeny']);
+ $newList = str_replace(array_keys($searchReplace), array_values($searchReplace), $row['explicit_allowdeny'] ?? '');
```

**Comment by mschwemer** [comment]
Solved with PR in2code-de/powermail#1074
