### ISSUE TITLE
TCA: Cleanup RTE configuration

### ISSUE THREAD

**Issue by julianhofmann** [in2code-de/powermail#1065]
While analyzing #262,  I stumble over old RTE configuration stuff.

Specifically: In TYPO3 v8.6 "defaultExtras" has already been removed, but Powermail still uses it (at least in FlexForms)
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/8.6/Deprecation-79341-TCARichtextConfigurationInDefaultExtrasDropped.html

Furthermore, I would also remove the "richtextConfiguration", as it is only initialized with "default", which TYPO3 automatically falls back to. However, not setting it would allow it to be overwritten via PageTS ( #262)

**Comment by mschwemer** [comment]
Solved with merged PR #1066
