### ISSUE TITLE
[Bug] Error when reversing history of plugin settings

### ISSUE THREAD

**Issue by haraldwitt** [in2code-de/powermail#1081]
Trying to reverse a change in a powermail plugin (receiver mail address in my case) via history leads to this error:

>Bei dem Versuch, die Elemente für Feld "processing66975b65eb57c577987873" (PHP Warning: Undefined array key "flexParentDatabaseRow" in /usr/www/users/yfsrww/develop/xxx/vendor/in2code/powermail/Classes/Tca/FormSelectorUserFunc.php line 70) zu verarbeiten, ist ein Fehler aufgetreten.

Typo3 12.4.16 / powermail 12.3.5

**Comment by mschwemer** [comment]
Thx for your report. 

I made a patch. It will be included in one of the next releases.

**Comment by mschwemer** [comment]
Solved with 77da91fede1686a64f955fb223984b99d30864bd
