### ISSUE TITLE
Flash messages not displayed if a redirect is configured in powermail plugin

### ISSUE THREAD

**Issue by sypets** [in2code-de/powermail#1108]
Maybe this is not a bug, but this is not something I was not aware of before and it has caused problems in cases where there were errors but these were not displayed. 

Perhaps its at least possible to document it.

## Reproduce

1. Create a working powermail form and include it in a plugin
2. Configure the plugin correctly
3. In the powermail plugin flexform, Configure a redirect page (tab "Submit Page": "Redirect to any other Page after submit". Use a page where there is **not** a powermail plugin

![image](https://github.com/user-attachments/assets/a828e3a0-1e01-4550-a617-0e4e0ee72702)

5. In the FE fill out the form causing an error (e.g. with a wrong email-address)

Now, we should see the flashmessages, but we do not because we have been redirected to a page without a powermail plugin. If we then switch back to the form, we see the flash messages.

## Versions

* TYPO3: 12.4.18
* powermail: 12.3.5

I am using a slightly patched powermail version, so the flash messages generally works (just not in this case), see also 

* #1087 
* #1100

## Possible solution

I tested the following and they seem to solve the problem:

* add a powermail plugin with an empty form on the redirect target page
* OR in your sitepage, always show the flash messages by adding this to your main template:

`<f:flashMessages queueIdentifier="extbase.flashmessages.tx_powermail_pi1"/>`

I don't know what would be the best solution for powermail, perhaps it is possible to add this to the documentation, create another plugin just to show the flash messages or someone has a better idea.

## Impact / severity of problem

Though we have a high throughput of powermail forms being used and it generally works great, the cases where it does not are quite time-consuming and problematic. In general, I would prefer it if the user gets a good error message and can either try again or report this. If no error is displayed, I am afraid, some problems might go undetected.

**Comment by mschwemer** [comment]
Documentation update in 709afac4f318186cfaedd6274c3e88d46fd77766
