### ISSUE TITLE
SendMailService does not send mails, mail validation is called wrong

### ISSUE THREAD

**Issue by rengaw83** [in2code-de/powermail#1112]
Before an mail is send, the address is validated:

https://github.com/in2code-de/powermail/blob/40c6b72247384edb633060c41e8253f6b0e2de69/Classes/Domain/Service/Mail/SendMailService.php#L99-L102

The validation of the `receiverEmail` is always wrong: `GeneralUtility::validEmail($email['receiverEmail'] === false)`. `GeneralUtility::validEmail` is always called with a `bool` value, not the mail address.  
The bracket is incorrectly placed.

The bug exists since version 11/12 and was integrated in 
https://github.com/in2code-de/powermail/commit/11b7b146039929a2f51bce660487ebceacd28253#diff-2d5d4d02fe84a8e6e4354363868cb6218f61c804b9d3e6ac6423cb75874028fdR97-R98

**Comment by rengaw83** [comment]
With the Following fix all works like expected again:
```diff
- if (GeneralUtility::validEmail($email['receiverEmail'] === false) || 
+ if (GeneralUtility::validEmail($email['receiverEmail']) === false || 
     GeneralUtility::validEmail($email['senderEmail']) === false) { 
     return false; 
 } 
```

I have created an PR for that: #1113

**Comment by mschwemer** [comment]
Thanks for your contribution. Merged it. :-)
