### ISSUE TITLE
Pagination in backend module is broken for listAction

### ISSUE THREAD

**Issue by vnc-jboe** [in2code-de/powermail#1118]
Powermail v12.3.5
TYPO3 v12.4.19

The pagination in the backend module for email lists is broken. When you try to click on a page number, the currentPage variable is set but the list page view still remains on page number 1.

I guess it's about the handling of page number in the listAction of ModuleController. I'm gonna write a fix now.

In powermail v12.4.0 is still the same bug.

**Comment by mschwemer** [comment]
Thanks for your contrib. Fixed with #1129
