### ISSUE TITLE
Undefined variable $isSavingOfMailAllowed

### ISSUE THREAD

**Issue by bergischweb** [in2code-de/powermail#1120]
[TYPO3 11, Powermail 10.8.1, PHP 8.1]

After updating Powermail from PM 9 to latest 10 I get the warning **"Undefined variable $isSavingOfMailAllowed in /public/typo3conf/ext/powermail/Classes/Controller/FormController.php line 225"** when confirming the double opt-in mail. 

Is there something I can do to get rid of this message?

**Comment by mschwemer** [comment]
Fixed with EXT:powermail 10.8.2.
