### ISSUE TITLE
[BUG] Mail is not sent when 2 different formulars are on the same page

### ISSUE THREAD

**Issue by jakobwid** [in2code-de/powermail#1121]
TYPO3: 12.4.19
Powermail: 12.4.0

Bug: Mail is not sent when 2 different formulars are on the same page. But it is always the second formular

While searching for the Bug, I tested different version of powermail and found out that two forms on the same page stopped working in powermail version 12.3.2.

I found that the newly added `initializeCreateAction` has to do with it, espacially the function `forwardIfFormParamsDoNotMatch` in it.

In the `forwardIfFormParamsDoNotMatch` is checked if the form uid, which is sent via request is equals the form uid in the settings.
Here a screenshot for reference: (line 610 in FormController.php)
![Bildschirmfoto vom 2024-09-06 11-34-49](https://github.com/user-attachments/assets/1ba4ad6f-7468-4b27-88d3-e6b48705cb29)

I don't know why but in the settings is the uid of the other form and therefore the request is not executed.
Here a screenshot for reference: (it should be 1 and 1)
![Bildschirmfoto vom 2024-09-06 11-40-33](https://github.com/user-attachments/assets/b5fbd61b-146b-4475-a922-6046cb0f4db6)

**Comment by atigiti** [comment]
I'm having the same issue.

**Comment by mschwemer** [comment]
I introduced this behavior with commit 8f4f5aa trying to solve #969. Sorry for that. I rolled back the commit.
