### ISSUE TITLE
[CLEANUP] CSS und JS

### ISSUE THREAD

**Issue by mschwemer** [in2code-de/powermail#1131]
Currently (most) JS and CSS is in `Resources/Build`. Files in there must be build via a gulp script, when they changed. 

As plain css is already quite powerful, we can move to that. 

Futhermore the loading of js got way better the last years with es6 modules. So we can move to that also.

I fear that this needs a lot of refactoring. 

If there is somebody out there, who has fun to work on that, you are really welcome. Please contact me via slack or email.

**Comment by pixeldasher** [comment]
I wouldn't mind working on this issue though I wonder what kind of refactoring you had in mind?

Rewrite all the assets using newer standards, just relocating the files and skipping the build step?

Are the resources needed only in the frontend or the backend, too?
TYPO3 kindly let's one use ES6 modules in the backend, I suppose you're thinking about that.
I tried setting them up in the frontend, but with caching and minify/compress/concatenation it's sadly not that easy.

Regardless, I would like to help here!

**Comment by mschwemer** [comment]
@pixeldasher Thanks for your offer. 🤗 

Since we have some more issues, like accessibility in this area, we decided to solve this internally at in2code. Reason is, that we can coordinate the efforts more easily. Sorry. 

I will close the issue here.
