### ISSUE TITLE
[Bug]Captcha validation problem

### ISSUE THREAD

**Issue by morange** [in2code-de/powermail#1137]
Hello,
I have the problem that I cannot send a Powermail form with Captcha Check. I have solved the captcha correctly several times. However, I keep getting the error message that the captcha code is wrong and I should try again. When I have managed it (by chance?), an e-mail is also sent.
I have not made any changes to the captcha in my TypoScript.

I can also reproduce the problem locally.

I use:
* PHP8.2
* Composer 
* TYPO3 v12.4.20
* Powermail 12.4.1
* DDEV (local)
* Provider is Mittwiald

I deleted the caches, reloaded the page, deleted Powermail and reinstalled it, used an very simple form with name, mail and captcha, commend out my TypoScript setup and constants. Nothing helped.

I hope, you can help me.

**Comment by mschwemer** [comment]
Talked about on slack. 

It was an issue with custom js.
