### ISSUE TITLE
Testmails in functions submodule are sent but there is no message

### ISSUE THREAD

**Issue by einpraegsam** [in2code-de/powermail#1144]
If I try to send a testmessage via powermail backend module with version 12.4.1, there is no message like "Message was sent" visible even if the mail can be received

**Comment by mschwemer** [comment]
Fixed in 51c19baecf4fef2985ecedded53f59952eae1560

The layout did not change since the initial commit. It is sending out a plain email. Using the default fluid template would be an enhancement, but has no priority right now
