### ISSUE TITLE
Opening a plugin over preview and closing it, will cause an error in TYPO3 12

### ISSUE THREAD

**Issue by einpraegsam** [in2code-de/powermail#1145]
I'm using powermail 12.4.1 in a customer project.
When I open the plugin by clicking the title of the plugin in the preview (that one with the pen icon beside), the plugin will be opened correctly. But when I then close the plugin, an error came up. It seems that the redirectUrl is wrong.

The final error message here:
```
Edit form could not be loaded
The edit form could not be loaded for the requested records. This might be due to insufficient permissions.
```

**Comment by mschwemer** [comment]
Fixed with fdee43f24e4cb5024968bbed44ecdb6be5f2625e

Will be in the next release
