### ISSUE TITLE
Predefined Receivers: is it possible to use same field twice?

### ISSUE THREAD

**Issue by zottelmann** [in2code-de/powermail#1197]
Hello!

Typo3 v10, Powermail V8.5.1 (will be upgraded soon, i promise ;))
Is it possible to use a field multiple times to get more than one receiver? The Predefined receivers example works so far, but i was wondering if its possible to do something like this:
```
emailA = CASE
emailA {
        key.data = GP:tx_powermail_pi1|field|fieldA
        12345678=TEXT
        12345678.value=mail@test.de
        default = TEXT
        default.value = defaultmail@test.de
}

#now checking the same field again:
emailB = CASE                            
emailB {
        key.data = GP:tx_powermail_pi1|field|fieldA
        key.stdWrap.crop = 3 | | 0
	123 = TEXT
	123.value = anothermail@test.de
	default = TEXT
        default.value = defaultmail@test.de
}

# now make a list of mails to be sent
plugin.tx_powermail.settings.setup.receiver.predefinedReceiver.receivers1.email = {emailA.value},{emailB.value}

```
The code is just a mockup. But would it be possible?

Regards

**Comment by julianhofmann** [comment]
`email` can be a comma-separated list of several e-mail addresses. And it can be any cObject. I.e. you only have to assemble the list correctly (i.e. with commas).
Your `emailA` and `emailB` Yare any cObjects. You can copy or reference these according to the normal TypoScript functionality to sub-objects within a cObject in `email`.

```
temp.emailA = TEXT
temp.emailA.value = me@example.com

plugin.tx_powermail.settings.setup.receiver.predefinedReceiver.receivers1.email = COA
plugin.tx_powermail.settings.setup.receiver.predefinedReceiver.receivers1.email {
  10 < temp.emailA
}
```

**Comment by zottelmann** [comment]
Hello!

Thank you, i am still trying to wrap my head around typoscript, but this hint helps!

Regards
