### ISSUE TITLE
FormController:create() within optinConfirm() ?

### ISSUE THREAD

**Issue by TrueType** [in2code-de/powermail#469]
This may relate to #376, #466   
Using TYPO3v9, EXT:powermail v9.4.0 and default Captcha.

the optinConfirmAction() does forward to the createAction() where all validations are run on the $mail object. For the captcha validation it wants to read the answer value from the session, which does not exist. I did not check, if it is deleted during initial POST and form validation. But as one can open the confirm link within another browser and session, it's of now relevance anyway. 

As I see it the create() action should only be called for object creation. optinConfirm is an update.

**Comment by mschwemer** [comment]
Thanks for your input

Is it just a technical question? Or do you encounter an error? 

I tested the default captcha with optin and confirmation and everything worked fine, using TYPO3 V9 and EXT:powermail 7.4.2

If you encounter an error, please provide more information. Error message, site configuration, typo3 and plugin setup.

**Comment by TrueType** [comment]
Hi. This is quite a long time ago. The input is rather technical. The basic structure of the controller actions and there usage is not ok. That is what I can remember. ..
Is powermail still actively maintained? My point would be for some major refactoring of the code. I guess this will never happen. But I might be wrong. 
Have a nice day.

**Comment by mschwemer** [comment]
Powermail is still actively maintained. :-) 

We plan to refactor the code step by step with the next releases.
