### ISSUE TITLE
[FEATURE] Possibility to access mail values in Signal Slots "setReceiverEmails"

### ISSUE THREAD

**Issue by phil64** [in2code-de/powermail#473]
Add this method in class ReceiverMailReceiverPropertiesService:
`public function getMail()
    {
        return $this->mail;
    }`
in order to give the possibilty to access the mail object in the Signal Slot implementation

**Comment by mschwemer** [comment]
Signal and Slots are outdated. 

We improved the corresponding event a lot. 

So I close this issue. 

If you think, we should add functionality to the corresponding event, please open a new issue for that. 

Thx.
