### ISSUE TITLE
Erroneous URLs in LinkViewHelper when using sub-directories 

### ISSUE THREAD

**Issue by twaurisch** [in2code-de/powermail#483]
In the LinkViewHelper class an absolute url is generated by default. It's used in the backend module for linking attached files. 

In line 33 the environment variable **TYPO3_SITE_PATH** is sanitized with `rtrim('/subfolder/', '/')`, which results in the following absolute url:
`https://www.domain.com//subfolderuploads/tx_powermail/jumwgjdl27hw4z11.pdf`

It works if TYPO3 runs in the document root, because the **TYPO3_SITE_PATH** _/_ is stripped away. If running TYPO3 in a sub-directory the wrong side of the site path is trimmed. 

To solve this is problem I would like to set up an array with all the important parts of the url, but without slashes at he beginning or the end of each part and implode it to an absolute url with _/_ at the end.

If you agree I could create a Pull Request.

**Comment by pixeldesu** [comment]
This has been fixed with e54b80dd115900307d0306add3541aa1a3e10da1 (since Powermail 12.3.3)
