### ISSUE TITLE
Field Title translations change to default language after submit

### ISSUE THREAD

**Issue by rschoenfeld** [in2code-de/powermail#499]
When using free mode as language fallback type and connected mode in powermail forms, translations for the field title change back to the default langauge after trying to submit and showing form errors.

TYPO3 9.5.13
powermail 7.4.0

**Comment by mschwemer** [comment]
You should really stay consistent in the used language modes within a website. I think this is an edge case and bad practise. 

Please check, if the problem still exists in V12. If yes, you can get paid support at in2code https://www.in2code.de/
