### ISSUE TITLE
Removal of exlude = true for l10n_parent field

### ISSUE THREAD

**Issue by georgringer** [in2code-de/powermail#515]
The exclude field must not be set for the field l10n_parent to avoid errors during translation and wrong user configuration. With 10 this setting is automatically removed with the TCA migration

> The 'tx_powermail_domain_model_answer' TCA tables transOrigPointerField 'l10n_parent' is defined as excluded field which is no longer needed and should therefore be removed.

**Comment by mschwemer** [comment]
Solved since a long time due to the mentioned commit above.
