### ISSUE TITLE
[DOCS] Update section on adding field properties

### ISSUE THREAD

**Issue by phvt** [in2code-de/powermail#521]
The [documentation for adding custom field properties](https://github.com/einpraegsam/powermail/blob/develop/Documentation/ForDevelopers/AddNewFieldProperties.md) is missing a TypoScript property for it to work in TYPO3 v9.5. For TYPO3 10, it's missing an Extbase PHP configuration file due to the removal of the configuration via TS (although I haven't tested that yet).

See: https://github.com/einpraegsam/powermailextended/issues/5#issuecomment-616257711

**Comment by mschwemer** [comment]
You are right. 

A rewrite of the documenation is already on the way. 

I will keep it open as a reminder.

**Comment by mschwemer** [comment]
Close it, since that it is a very, very old version. 

If you think, we should add it to the current docs, please re-open the issue and provide a PR for the current version.
