### ISSUE TITLE
Broken Link in optin mail in plaintext mails

### ISSUE THREAD

**Issue by kanow** [in2code-de/powermail#542]
powermail v7.4.0, TYPO3 9.5.17

The confirmation link in plaintext mails is broken. I think there are 2 problems in powermail/Classes/Domain/Service/Mail/PlaintextService.php in `extractLinkForPlainTextContent()`

first: missing `htmlspecialchars_decode` for the linktext if the link text is also a url. Url with &amp; produces a 404 error if I click the link in thunderbird. Maybe only add `htmlspecialchars_decode` if the link text is really an url.

second: missing space character after the link before the closing `]`.

Correct me if I'm wrong.

**Comment by mschwemer** [comment]
Tested it with the current master branch. 

I cannot confirm this issue any more. So I am closing it.

If you are still hit by the issue, please re-open it with more detailed information.
