### ISSUE TITLE
content of (one) form missing in exported files

### ISSUE THREAD

**Issue by peerlight** [in2code-de/powermail#543]
WEB > powermail shows "mails" for two forms on a page

without filtering for form1 or form2
- table shows mails of form1 and form2
- CSV-File misses rows of form2 completely
- XLS-File has empty rows where content of form2 should be

with filtering everything is ok

the forms are configured in a way that there are no mails sent to recepient nor sender

powermail 7.4.0 on TYPO3 9.5.14

**Comment by mschwemer** [comment]
Since Powermail v7 many things changed.  

Can you confirm this behaviour on TYPO3 v12 with EXT:powermail v12?
