### ISSUE TITLE
Ajax submit very slow on big pages

### ISSUE THREAD

**Issue by ffh-webadmin** [in2code-de/powermail#546]
When inserting powermail forms with activated ajax submit on pages with a lot of content elements, it will take very long to submit the form and getting the response. Powermail seems to render the complete page in the background and only to extract the responce page via Javascript from the ajax response.

We think the submit process should be much faster if powermail would only render the content of its own response page.

**Comment by mschwemer** [comment]
Since TYPO3 and EXT:powermail changed a lot since then and there is no +1 or any other comments, I close this issue. 

If you still have an issue with it, please re-open the issue and / or contact in2code (https://www.in2code.de/) for paid support
