### ISSUE TITLE
No confirmation-mail with double-opt-in!?

### ISSUE THREAD

**Issue by kurtkk** [in2code-de/powermail#551]
I fill a form and push the send-button.
"double-opt-in" is checked in the BE-powermail-plugin.

I do not get the confirmation-mail with the link to confirm my correct e-mail-address!?

What happened resp. where is my failure?

Thank's in advance
Kurt Kunig

**Comment by MrMooky** [comment]
Which Powermail version are you using? Might be related to https://github.com/einpraegsam/powermail/issues/557

**Comment by kurtkk** [comment]
Version 7.4.0 and powermail_cond 7.0.0

**Comment by MrMooky** [comment]
@kurtkk Check the PR suggested the #557.

**Comment by christophbee** [comment]
I am also faced with the same issue: 

powermail 8.2.4 
TYPO3 10.4.10
"double opt-in" enabled in flexform

When submitting the form I do not receive the mail with the confirmation link whereas without double opt-in sending the mail  is working. I already looked up issue #557 and adjusted my settings according to that but that did not solve my problem.

When I look up the mails stored in backend the double opt-in mails are hidden by default: What does this mean?
![Bildschirmfoto 2020-12-18 um 09 59 37](https://user-images.githubusercontent.com/22295289/102595684-4ce48f80-4118-11eb-9dab-6816840b9bbb.png)

**Comment by agendartobias** [comment]
Same problem here with 8.4.1

**Comment by astoun** [comment]
I have same problem (Typo3 10.4.27, powermail 8.3.2).
I think the confirmation email is generated incorrectly. When I look at the list of emails in BackEnd I see the address waiting for confirmation.

![678](https://user-images.githubusercontent.com/9988116/165532395-e87aef23-52a7-4ac4-b8b7-aa50bdd7a6a2.jpg)

And if I open it in the BackEnd, then I see in the Email text some debug code - that is wrong:
![679](https://user-images.githubusercontent.com/9988116/165532433-fd414125-27c7-4f3a-8b22-65535ae8034d.jpg)

Any ideas how to fix it??

**Comment by christophbee** [comment]
This error only occurs when $GLOBALS['TYPO3_CONF_VARS']['MAIL']['defaultMailReplyToAddress'] is empty. After I entered a valid mail adresse everything works. 

see https://github.com/einpraegsam/powermail/issues/557#issuecomment-743224412

**Comment by mschwemer** [comment]
We have this case in our testing evironment and cannot confirm the issue for v12. 

If you are still hit by the issue, feel free to re-open it.
