### ISSUE TITLE
Variable powermail_all stripped from output

### ISSUE THREAD

**Issue by datamints-off** [in2code-de/powermail#760]
In a (more or less) blank TYPO3 11 installation with the latest version of EXT:powermail installed, the variable "powermail_all" gets stripped from the output in mail and website text.
Reason seems to be the parseFunc used: if I switch this from lib.parseFunc_RTE to lib.parseFunc, the variable is there again.

**Comment by mschwemer** [comment]
As I cannot confirm it in our test environment and there are no other comments / issues regarding this, I close the issue now.

If you are still hit by the problem, do not hesitate to reopen this issue.
