### ISSUE TITLE
Handling of configured email addresses 

### ISSUE THREAD

**Issue by mschwemer** [in2code-de/powermail#761]
There are currently several issues and pull requests open, regarding the topic of e-mail addresses and SPF. 

I think, we must review and (maybe) refactor this area. 

This ticket is to collect all open tickets and PRs to have an overview: 

* #737 impossible to overwrite receiver senderEmail when double-opt-in is active
* #692 Disclaimer mail doesn't use correct sender mail
* #668 ReturnPath not working anymore
* #557 plugin.tx_powermail.settings.setup.receiver.overwrite.replyToEmail.value is ignored
* #502 SPF-Issue with yahoo-mails and replytoEmail for receiver
* #742 respect sender.default.senderEmail for sender mail TO fallback
* #677 [BUGFIX] set sender instead of returnPath 
* #630 [BUGFIX] empty replyToEmail error for optin mails if settings.flexfor

**Comment by einpraegsam** [comment]
Some of the issues should be fixed with #772 now

**Comment by mschwemer** [comment]
Can be closed as all referenced issues / prs are resolved, deleted or merged
