### ISSUE TITLE
Backend-module: XLS export went wrong

### ISSUE THREAD

**Issue by tobikummer** [in2code-de/powermail#770]
**TYPO3 11 LTS
Powermail 9.0.x
PHP 7.4.29**

In the backend module of powermail, there is a list view of all the sent mails. The CSV-export is great, but not the XLS export.
<img width="1357" alt="Bildschirmfoto 2022-05-19 um 10 55 00" src="https://user-images.githubusercontent.com/19902193/169255474-d939425b-8fea-4934-8258-b1636b87b618.png">
 
The result of the XLS export is having all the mail data as plain text in the browser...
<img width="1375" alt="Bildschirmfoto 2022-05-19 um 10 55 26" src="https://user-images.githubusercontent.com/19902193/169255568-ed2b232a-d78f-4a77-8b6f-180534e09c5f.png">

Tested in 3 different TYPO3 11 instances with powermail 9.0.x

**Comment by LimeUwe** [comment]
+1

**Comment by einpraegsam** [comment]
I just tested on my machine and can't see a problem. Tested on Firefox on Ubuntu.

**Comment by CIMEOS** [comment]
I, we have the same issue since ~V9
Instead of exporting to xls, it renders the data as an html table.

Tested on Brave Version 1.39.122 (Chromium: 102.0.5005.115)
and Firefox Version 91.10.0esr

Typo3 Version 11.5.12
PHP Version 7.4.3

**Comment by dennismetz** [comment]
We have a similar error with the export.
XLS works with the default fields, CSV not at all.

As soon as a field is selected under "advanced export" (e.g. disabled) I get a 500 error.

Is there any news on this yet?

TYPO3 10.4.30
Powermail: 8.4.1
PHP: 7.4.6 (7.4.30)
Firefox: 102.0

**Comment by Apen** [comment]
For me it was fix since 10.2.0 (was in 10.1.0 before)

**Comment by mschwemer** [comment]
We reworked the excel export in one of the last versions completly. 

If you still need assistance with it, you can get payed support at in2code https://www.in2code.de/
