### ISSUE TITLE
French translation of datepicker_format_date

### ISSUE THREAD

**Issue by fazzyx** [in2code-de/powermail#817]
The Date format for French translation is wrong.
We get from the language file "A-m-j" for "datepicker_format_date" in French language

```
<trans-unit id="datepicker_format_date" resname="datepicker_format_date" approved="yes">
  <source>Y-m-d</source>
  <target state="final">A-m-j</target>
</trans-unit>
```

**Comment by fazzyx** [comment]
This is managed by crowdin and there is already a comment to the wrong format. 7 month ago...
Do anybody know what to do at crowdin to set the correct entry?

**Comment by einpraegsam** [comment]
Sorry, I don't have a clue how to handle crowdin :)

**Comment by mschwemer** [comment]
@fazzyx What would be the right one? `Y-m-d`?

**Comment by fazzyx** [comment]
@mschwemer  
I'm not sure but dd/mm/yyyy or yyyy-mm-dd (depends on region) according to
https://en.wikipedia.org/wiki/Date_format_by_country
or from https://en.wikipedia.org/wiki/Slash_(punctuation)
"France most commonly records the date using the day-month-year format with an oblique stroke or slash"
However , they do not use A-m-j:)

**Comment by mschwemer** [comment]
@fazzyx It is fixed in crowdin. 

Can you confirm it on your side? If yes, I would close the issue.

**Comment by mschwemer** [comment]
Closing it, since there was no response. 

If you are still hit by the issue, please re-open it. 

Thx.
