### ISSUE TITLE
Bug: Missing type casts

### ISSUE THREAD

**Issue by tastendruecker** [in2code-de/powermail#848]
Hi!
I found two occurrences where missing type casting breaks PHP's strict typing:

1. When calling getPageIdentifierFromExistingContentElements() in In2code\Powermail\Tca\ShowFormNoteEditForm::getPageIdentifierForNewForms() (Line 179) passed parameter $this->data['databaseRow']['pid'] must be cast to int
2. In \In2code\Powermail\Tca\ShowFormNoteIfNoEmailOrNameSelected::senderEmailOrSenderNameSet() (Line 129) $this->data['databaseRow']['uid'] must be cast to int before assigned to variable $formIdentifier.

**Comment by tastendruecker** [comment]
Found another missing type cast in In2code\Powermail\Tca\ShowFormNoteIfNoEmailOrNameSelected::hasFormUniqueAndFilledFieldMarkers() (line 181). Please make sure your code casts all values fetched from arrays, like e.g. database rows.

**Comment by einpraegsam** [comment]
Hi, please give us some more information.
In general: What TYPO3, PHP and Powermail version is in use?
For every issue: What should I do to reproduce such an issue? E.g. login into backend as admin, open a plugin of list_type powermail_pi1, and so on...

**Comment by tastendruecker** [comment]
Hi einpraegsam,

Thanks for your replay.

We're experiencing this independently from a specific TYPO3 version. Currently in use are 
- TYPO3 11.5.19 with powermail 10.7.0, PHP 7.4.30 and MySQL 5.7
- TYPO3 10.4.32, with powermail 8.4.2, PHP 7.4.32 and MySQL 5.7

You may reproduce missing type castings for example if you try to edit a powermail form in the TYPO3 backend that has no field marked as name or email. Depending on PHP setup and/or TYPO3 environment you may receive TYPO3 exceptions or no output at all. 

But this is a systematic bug. The code uses array values from a Doctrine DB result without any validation or casting. But as https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Database/Statement/Index.html states (within the orange warning box): The return values are not type safe. Depending on the environment, DB servers may return typed values or just strings. So, the application has to make sure that type casting is performed before values are used.
