### ISSUE TITLE
PHP Error: Array to string conversion in SpamNotification-Mail with Checkboxes

### ISSUE THREAD

**Issue by olivermeckel** [in2code-de/powermail#851]
When a contact request is detected as spam by Powermail, I get a php error message in the log: 

Core: Error handler (FE): PHP Warning: Array to string conversion in /html/typo3/typo3_src-11.5.21/vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/AbstractNode.php line 73

In addition to simple input fields, textareas, dropdowns and so on, the form also contains input fields of the type checkboxes (with multiple values). The output of multiple values in the sender and receiver mails as well as in the back end is correct. In the spam notification mail and log, the output is as text "array".

TYPO3 11.5.21
Powermail 10.7.0
PHP 8.1.12

**Comment by olivermeckel** [comment]
Is it the missing check whether the answer is a string or an array in the templates for the SpamNotifaction?{vh:condition.isArray(val:answer.value)}

Is there a way to send/test the spamnotification log or mail by system?

**Comment by einpraegsam** [comment]
I just tried to reproduce this issue with PHP 8.0 and the lastest powermail but there is no issue in my eyes:
![Screenshot 2023-02-13 at 11-52-42 Powermail for TYPO3 11 active (Log)](https://user-images.githubusercontent.com/89055/218439077-1b236443-8454-4828-90cc-0f6382bde202.png)

Any hints how to reproduce it?

**Comment by olivermeckel** [comment]
Hi Alex,

just to clarify: it's a php-error reported in the typo3 backend when spameshield detects an spam and send a spamnotification by mail or log using the template

**Comment by einpraegsam** [comment]
Ah, ok - I can read the error in the log:
```
  | Core: Error handler (FE): PHP  Warning: Array to string conversion in  /var/www/html/powermail11.localhost.de/vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/AbstractNode.php  line 73
-- | --
```

**Comment by olivermeckel** [comment]
I changed the code for providing the form variables ind the spam notification template to:

```
<f:for each="{mail.answers}" as="answer">
    <f:if condition="{vh:condition.isArray(val:answer.value)}">
        <f:else>
            - {answer.field.title}: {answer.value}
        </f:else>
        <f:then>
            <f:for each="{answer.value}" as="subValue" iteration="index">
                <f:if condition="{subValue}">
                    <vh:misc.manipulateValueWithTypoScript answer="{answer}" type="{type}">{subValue}</vh:misc.manipulateValueWithTypoScript><f:if condition="{index.isLast}"><f:else>, </f:else></f:if>
                </f:if>
            </f:for>
        </f:then>
    </f:if>
</f:for>

```
No more php-errors

**Comment by olivermeckel** [comment]
By the way, Spamshield works great and detects 100% of spam requests. Great feature!

**Comment by pitscribble** [comment]
Thanks for the code snippet @olivermeckel, solved the problem for me too.

TYPO3 11.5
Powermail 10.7.3
PHP 8.1

**Comment by mschwemer** [comment]
As the comment in the last PR states, it is fixed in powermail v12. 

If you need a backport to powermail v10 / TYPO3 v11 please contact in2code https://www.in2code.de/
