### ISSUE TITLE
[BUG] Sender mail sent even if no mail address is given

### ISSUE THREAD

**Issue by haraldglaser** [in2code-de/powermail#856]
When no valid sender address is given, the sender mail (if generally activated) is sent to the address defined in $GLOBALS['TYPO3_CONF_VARS']['MAIL']['defaultMailFromAddress'].
This seems illogical and the code suggests that it was not planned that way, because sending of the mail is explicitly wrapped in this condition:
`if ($this->isSenderMailEnabled() && $this->mailRepository->getSenderMailFromArguments($mail)) {`

But `MailRepository::getSenderMailFromArguments()` is always true, as it finally falls back to `$GLOBALS['TYPO3_CONF_VARS']['MAIL']['defaultMailFromAddress']`, rendering the condition useless. (This behaviour clearly makes sense for the from-header of the receiver-mail, where this function is also used, but not for determining the address to send a confirmation mail to...)

Note: there are valid use cases, where a sender mail is configured but no sender mail address is submitted in the form data, e.g. the user can choose to be contacted by mail or phone, thus making the mail field not required (or even hiding it with Powermail Conditions).

**Comment by mschwemer** [comment]
Solution is, that you leave the sender subject empty, as stated in the docs and in the plugins flexforms.

**Comment by haraldglaser** [comment]
I disagree, the proposed solution is not a solution at all for the stated valid use case:
- the field for the user e-mail-address is not mandatory
- if an email is given, the user should get a confirmation mail
- if no sender email is given, it makes absolutely no sense to send the confirmation mail to the defaultMailFromAddress instead
Leaving the subject empty does not cover the case where an email is given.

**Comment by cweiske** [comment]
I also experience this problem: The e-mail field is not mandatory, but the confirmation mail to the user is sent even if the field is not filled. I want the mail to be sent when the field is filled, but not when it has not been filled.

@mschwemer please reopen this issue.
