### ISSUE TITLE
obsolete translation files in project folder Resources/Language?

### ISSUE THREAD

**Issue by medarob** [in2code-de/powermail#896]
Hi,

I noticed that one of the excluded fields had a typo error:
![grafik](https://github.com/einpraegsam/powermail/assets/33951787/b50a9b7e-bdf0-4c15-9c10-4b0226cd1bbe)

I looked at the language files in `public/typo3conf/ext/powermail/Resources/Private/Language/de.locallang_db.xlf` and there was no typo and the correct string.

However, in `var/labels/de/powermail/Resources/Private/Language/de.locallang_db.xlf` the typo exists.

So I checked crowdin, where the translated files exist, and there was the error again.

I added the correct translation in crowdin so if it gets approved, the error will be gone after the next language update:
![grafik](https://github.com/einpraegsam/powermail/assets/33951787/26118917-4dbd-4998-8f91-4ac4e3138e6a)

As for the translated language files in `ext:powermail/Resources/Private/Language/`, starting with `de.*`, I would say that those can be deleted because they are unused and managed via crowdin? The only usage would happen if a user doesn't update the language files via the backend but as soon someone uses the language update function the local translations are obsolete, or?

**Comment by mschwemer** [comment]
Thanks. 

You are right. It is already on our internal list since a couple of weeks.

We will change that soon.
