### ISSUE TITLE
Frontend XHR validation for slow backend responses

### ISSUE THREAD

**Issue by kszymukowicz** [in2code-de/powermail#907]
hi

I 'd like to ask what is suggested way to write validators for frontend for situations when validation is XHR and backend response is like few second.

The problematic part is especially `field.addEventListener('input'` in file `FormValidation.js` which triggers XHR check for every single char written by user to input.

```
  #validateFieldListener() {
    const fields = this.#getFieldsFromForm();
    fields.forEach((field) => {
      field.addEventListener('input', () => {
        // When user types something in a field
        this.#validateField(field);
      });
      field.addEventListener('blur', () => {
        // When field focus gets lost
        this.#validateField(field);
      });
      field.addEventListener('change', () => {
        // When a checkbox, radiobutton or option in a select was chosen
        this.#validateField(field);
      });
    });
  };
```

I thought I can do something on `addSubmitErrorCallback` but there is no way on this level to say "set error to field A".

I'd be grateful for any suggestions! Tnx.

**Comment by mschwemer** [comment]
Sorry for the late response. 

If you need support, you can contact in2code https://www.in2code.de/ or use the TYPO3 slack channel.
