### ISSUE TITLE
Case: when plugin added inside IRRE / inline - wrong returnUrl for record edit form 

### ISSUE THREAD

**Issue by olegkarun** [in2code-de/powermail#908]
TYPO3: 11.5.27
Powermail: 10.7.2
News: 9.4.0 - but tested with custom  IRRE / inline - same result
PHP Version:	7.4.3

Case if added Powermail Plugin as content element of IRRE / inline filed. For example 
EXT: news 
-> News item (Entry)
-> Content elements (filed) 
-> add Powermail plugin 
-> click for edit related form
-> close related form 
-> we will get error 500

Problem that in this case edit link have wrong `returnUrl` as `/typo3/ajax/record/inline/details?token...` but should be something from parent element like News Item in this case. like it work for FAL. Example
`=edit&returnUrl=/typo3/record/edit?token=...&edit[tx_news_domain_model_news][..]=edit
&returnUrl=/typo3/module/web/list?token=...&id=163&table=&pointer=1&route=/record/edit#` instead `=edit&returnUrl=/typo3/ajax/record/inline/details?token=...`

**Comment by markustobler** [comment]
I have a similar problem using powermail_pi1 content element as TCA inline filed:

My TCA:
` 'form' => [
            'exclude' => false,
            'label' => 'LLL:EXT:sitepackage/Resources/Private/Language/locallang_db.xlf:tx_sitepackage_domain_model_event.form',
            'config' => [
                'type' => 'inline',
                'foreign_table' => 'tt_content',
                'minitems' => 0,
                'maxitems' => 1,

                'overrideChildTca' => [
                    'types' => [
                        'list' => [
                            'showitem' => 'CType,colPos',
                        ],
                    ],
                    'columns' => [
                        'CType' => [
                            'config' => [
                                'default' => 'powermail_pi1',
                            ],
                        ],
                        'colPos' => [
                            'config' => [
                                'default' => 10,
                            ]

                        ]
                    ],
                ],
                'appearance' => [
                    'collapseAll' => 0,
                    'levelLinksPosition' => 'top',
                    'showSynchronizationLink' => 1,
                    'showPossibleLocalizationRecords' => 1,
                    'showAllLocalizationLink' => 1
                ],
            ],
        ],`
        
        Error Log:
        `Thu, 08 Aug 2024 12:36:24 +0000 [CRITICAL] request="8fb37150cf4db" component="TYPO3.CMS.Core.Error.DebugExceptionHandler": Core: Exception handler (WEB: BE): TypeError, code #0, file /var/www/html/vendor/in2code/powermail/Classes/Tca/ShowFormNoteEditForm.php, line 190: In2code\Powermail\Tca\ShowFormNoteEditForm::getPageIdentifierFromExistingContentElements(): Argument #1 ($pageIdentifier) must be of type int, string given, called in /var/www/html/vendor/in2code/powermail/Classes/Tca/ShowFormNoteEditForm.php on line 175- TypeError: In2code\Powermail\Tca\ShowFormNoteEditForm::getPageIdentifierFromExistingContentElements(): Argument #1 ($pageIdentifier) must be of type int, string given, called in /var/www/html/vendor/in2code/powermail/Classes/Tca/ShowFormNoteEditForm.php on line 175, in file /var/www/html/vendor/in2code/powermail/Classes/Tca/ShowFormNoteEditForm.php:190 - {"mode":"WEB","application_mode":"BE","exception_class":"TypeError","exception_code":0,"file":"/var/www/html/vendor/in2code/powermail/Classes/Tca/ShowFormNoteEditForm.php","line":190,"message":"In2code\\Powermail\\Tca\\ShowFormNoteEditForm::getPageIdentifierFromExistingContentElements(): Argument #1 ($pageIdentifier) must be of type int, string given, called in /var/www/html/vendor/in2code/powermail/Classes/Tca/ShowFormNoteEditForm.php on line 175","request_url":"https://kantiwattwil.ddev.site/typo3/ajax/record/inline/create?token=--AnonymizedToken--","exception":"TypeError: In2code\\Powermail\\Tca\\ShowFormNoteEditForm::getPageIdentifierFromExistingContentElements(): Argument #1 ($pageIdentifier) must be of type int, string given, called in /var/www/html/vendor/in2code/powermail/Classes/Tca/ShowFormNoteEditForm.php on line 175 and defined in /var/www/html/vendor/in2code/powermail/Classes/Tca/ShowFormNoteEditForm.php:190\nStack trace:\n#0 /var/www/html/vendor/in2code/powermail/Classes/Tca/ShowFormNoteEditForm.php(175): In2code\\Powermail\\Tca\\ShowFormNoteEditForm->getPageIdentifierFromExistingContentElements()\n#1 /var/www/html/vendor/in2code/powermail/Classes/Tca/ShowFormNoteEditForm.php(162): In2code\\Powermail\\Tca\\ShowFormNoteEditForm->getPageIdentifierForNewForms()\n#2 /var/www/html/vendor/in2code/powermail/Classes/Tca/ShowFormNoteEditForm.php(84): In2code\\Powermail\\Tca\\ShowFormNoteEditForm->getNewFormLink()\n#3 /var/www/html/vendor/in2code/powermail/Classes/Tca/ShowFormNoteEditForm.php(62): In2code\\Powermail\\Tca\\ShowFormNoteEditForm->getHtml()\n#4 /var/www/html/vendor/typo3/cms-backend/Classes/Form/Container/FlexFormElementContainer.php(132): In2code\\Powermail\\Tca\\ShowFormNoteEditForm->render()\n#5 /var/www/html/vendor/typo3/cms-backend/Classes/Form/Container/FlexFormTabsContainer.php(82): TYPO3\\CMS\\Backend\\Form\\Container\\FlexFormElementContainer->render()\n#6 /var/www/html/vendor/typo3/cms-backend/Classes/Form/Container/FlexFormEntryContainer.php(49): TYPO3\\CMS\\Backend\\Form\\Container\\FlexFormTabsContainer->render()\n#7 /var/www/html/vendor/typo3/cms-backend/Classes/Form/Container/SingleFieldContainer.php(136): TYPO3\\CMS\\Backend\\Form\\Container\\FlexFormEntryContainer->render()\n#8 /var/www/html/vendor/typo3/cms-backend/Classes/Form/Container/PaletteAndSingleContainer.php(153): TYPO3\\CMS\\Backend\\Form\\Container\\SingleFieldContainer->render()\n#9 /var/www/html/vendor/typo3/cms-backend/Classes/Form/Container/TabsContainer.php(87): TYPO3\\CMS\\Backend\\Form\\Container\\PaletteAndSingleContainer->render()\n#10 /var/www/html/vendor/typo3/cms-backend/Classes/Form/Container/FullRecordContainer.php(78): TYPO3\\CMS\\Backend\\Form\\Container\\TabsContainer->render()\n#11 /var/www/html/vendor/typo3/cms-backend/Classes/Form/Container/InlineRecordContainer.php(240): TYPO3\\CMS\\Backend\\Form\\Container\\FullRecordContainer->render()\n#12 /var/www/html/vendor/typo3/cms-backend/Classes/Form/Container/InlineRecordContainer.php(123): TYPO3\\CMS\\Backend\\Form\\Container\\InlineRecordContainer->renderChild()\n#13 /var/www/html/vendor/typo3/cms-backend/Classes/Controller/FormInlineAjaxController.php(137): TYPO3\\CMS\\Backend\\Form\\Container\\InlineRecordContainer->render()\n#14 /var/www/html/vendor/typo3/cms-backend/Classes/Http/RouteDispatcher.php(77): TYPO3\\CMS\\Backend\\Controller\\FormInlineAjaxController->createAction()\n#15 /var/www/html/vendor/typo3/cms-backend/Classes/Http/RequestHandler.php(104): TYPO3\\CMS\\Backend\\Http\\RouteDispatcher->dispatch()\n#16 /var/www/html/vendor/typo3/cms-core/Classes/Middleware/ResponsePropagation.php(34): TYPO3\\CMS\\Backend\\Http\\RequestHandler->handle()\n#17 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Core\\Middleware\\ResponsePropagation->process()\n#18 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/SiteResolver.php(64): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#19 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\SiteResolver->process()\n#20 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/SudoModeInterceptor.php(51): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#21 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\SudoModeInterceptor->process()\n#22 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/AdditionalResponseHeaders.php(37): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#23 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\AdditionalResponseHeaders->process()\n#24 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/ContentSecurityPolicyHeaders.php(50): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#25 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\ContentSecurityPolicyHeaders->process()\n#26 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/OutputCompression.php(43): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#27 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\OutputCompression->process()\n#28 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/BackendModuleValidator.php(72): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#29 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\BackendModuleValidator->process()\n#30 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/BackendUserAuthenticator.php(159): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#31 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\BackendUserAuthenticator->process()\n#32 /var/www/html/vendor/typo3/cms-core/Classes/Middleware/RequestTokenMiddleware.php(71): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#33 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Core\\Middleware\\RequestTokenMiddleware->process()\n#34 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/BackendRouteInitialization.php(80): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#35 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\BackendRouteInitialization->process()\n#36 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/ContentSecurityPolicyReporter.php(41): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#37 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\ContentSecurityPolicyReporter->process()\n#38 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/ForcedHttpsBackendRedirector.php(55): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#39 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\ForcedHttpsBackendRedirector->process()\n#40 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/LockedBackendGuard.php(71): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#41 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\LockedBackendGuard->process()\n#42 /var/www/html/vendor/typo3/cms-core/Classes/Middleware/NormalizedParamsAttribute.php(41): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#43 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Core\\Middleware\\NormalizedParamsAttribute->process()\n#44 /var/www/html/vendor/typo3/cms-core/Classes/Middleware/VerifyHostHeader.php(55): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#45 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Core\\Middleware\\VerifyHostHeader->process()\n#46 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(70): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#47 /var/www/html/vendor/typo3/cms-core/Classes/Http/AbstractApplication.php(80): TYPO3\\CMS\\Core\\Http\\MiddlewareDispatcher->handle()\n#48 /var/www/html/vendor/typo3/cms-backend/Classes/Http/Application.php(58): TYPO3\\CMS\\Core\\Http\\AbstractApplication->handle()\n#49 /var/www/html/vendor/typo3/cms-core/Classes/Http/AbstractApplication.php(92): TYPO3\\CMS\\Backend\\Http\\Application->handle()\n#50 /var/www/html/public/typo3/index.php(20): TYPO3\\CMS\\Core\\Http\\AbstractApplication->run()\n#51 /var/www/html/public/typo3/index.php(21): {closure}()\n#52 {main}"}
`

**Comment by mschwemer** [comment]
Hi

just re-reading this issue ... puuh. 

Powermail was never intended to be used in an content element in news or as an inline element in a custom tca.  

I consider it as an "edge-case" and close it right now. 

If you do not confirm, feel free to re-open this issue or ask at [in2code](https://www.in2code.de/) for paid support.
