### ISSUE TITLE
CSV Export with a missing field

### ISSUE THREAD

**Issue by typo3-solution** [in2code-de/powermail#914]
Hi everyone.
Have I found an bug or am I the bug? ;-)
If i export the Mails with a missing field (using TYPO3V11):
![image](https://github.com/in2code-de/powermail/assets/11961924/0083df4b-6e5d-47a8-99f0-e20d341d6c7f)
i get diffrent results in the export:
![image](https://github.com/in2code-de/powermail/assets/11961924/bf3f7a01-f916-467f-ac0b-47f37e46367d)
Line 4 is the problem. The XLS is correct, the CSV is incorrect. 

Am I seeing this correctly or am I doing something wrong?

**Comment by mschwemer** [comment]
This was already fixed. I cannot reproduce it with the lastest release.

If you are still hit by the issue, feel free to re-open the issue
