### ISSUE TITLE
XLS Export in backend module exports only html table

### ISSUE THREAD

**Issue by metapublic-gbr** [in2code-de/powermail#922]
After updating from v9.0.2 to actual 10.7.3  (TYPO3 11.5.26, PHP 7.4) xls export is not working any more. After exporting a filtered Selection of Mails i get file namend powermail.xls but this file contains the all fields as html table. 

CSV-Export is working fine. 

There is a minor bug in the interface too: When choosing the date from / to with the drop down wizard the time is missing. I had to add the time manually. 

Tested in Chrome and Firefox.

**Comment by metapublic-gbr** [comment]
:-) OK, ich habe gerade gemerkt, dass Excel eine HTML-Tabelle tatsächlich öffnen kann, und damit das format doch stimmt. Ich konnte das nicht testen, weil ich Excel nicht besitze, und meine Tabellenkalkulation es tatsächlich nicht öffnen kann. Also schließen wir das hier mal wieder ...

**Comment by mschwemer** [comment]
Thanks for updating the issue. 

Nevertheless it's on our internal agenda to provide a native excel export, since there are issues with newer version of ms excel.
