### ISSUE TITLE
.project-folder in Extension package?

### ISSUE THREAD

**Issue by LUKAnetconsultGmbH** [in2code-de/powermail#923]
Hi there,

not really a critical issue but problably one that can easily be "fixed".

It seems that the .projects-folder is checked in the Extension package - is this really needed?

The following tar.gz files are included
- ext/powermail/.project/data/db.sql.gz
- ext/powermail/.project/data/fileadmin.tar.gz

and this triggers a warning from a server-sided script on our servers that checks for archives older than 60 days (so we don't keep old archives on the servers, probably DB-Dumps with login informations... ;) 

As I mentioned before, nothin serious, but a "nice to have" - or perhaps this is needed and I don't get it... :-D

Thank you and all the best,
 Christoph

**Comment by mschwemer** [comment]
Thanks for ypour hint. Excluded it in commit 046d3ca2d1241eeafd418818a7645da0c0666b1c. 

Will be in the next release
