### ISSUE TITLE
Uncaught TYPO3 Exception In2code\Powermail\Update\PowermailPluginUpdater::updateContentElement()

### ISSUE THREAD

**Issue by alandolsi** [in2code-de/powermail#926]
Error When  Running Wizard "Powermail: Migrate list types and switchable controller actions to CTypes"

Uncaught TYPO3 Exception In2code\Powermail\Update\PowermailPluginUpdater::updateContentElement(): Argument #3 ($flexform) must be of type string, null given, called in /var/www/html/vendor/in2code/powermail/Classes/Update/PowermailPluginUpdater.php on line 154
thrown in file /var/www/html/vendor/in2code/powermail/Classes/Update/PowermailPluginUpdater.php
in line 224

Powermail Early Access for TYPO3 v12

possible fix

<img width="560" alt="image" src="https://github.com/in2code-de/powermail/assets/3594182/530f295c-dadd-45e9-9191-7a41a1a332b9">

Thank you

**Comment by abvdveen** [comment]
Encountered same error when upgrading Powermail. Suggested fix solves it: generates correct new instances of powermail_pi1.

**Comment by vertexvaar** [comment]
I suggest another patch

```
Index: Classes/Update/PowermailPluginUpdater.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/Classes/Update/PowermailPluginUpdater.php b/Classes/Update/PowermailPluginUpdater.php
--- a/Classes/Update/PowermailPluginUpdater.php	
+++ b/Classes/Update/PowermailPluginUpdater.php	(date 1717502423326)
@@ -134,7 +134,7 @@
                 }
             } else {
                 $targetCType = 'powermail_pi1';
-                $newFlexform = $record['pi_flexform'];
+                $newFlexform = $record['pi_flexform'] ?? '';
             }
 
             // Remove flexform data which do not exist in flexform of new plugin

```

**Comment by mschwemer** [comment]
Fixed with merged PR
