### ISSUE TITLE
Captcha not working since TYPO3 11.5.33

### ISSUE THREAD

**Issue by woemar** [in2code-de/powermail#940]
TYPO3: 11.5.33
Powermail: 10.7.4

Since updating to TYPO3 11.5.33 the powermail captcha will always be wrong.

Observation: The image in FE is NOT the image stored under /typo3temp/assets/tx_powermail, e.g. in FE you'll see "11+2" but the image in /typo3temp/assets/tx_powermail will display e.g. "7-3"

Providing the answer fitting the image in /typo3temp/assets/tx_powermail will indeed solve the captcha and display the summary page of the form. Sending the form will not work, I get redirected to an empty form.

Expected bahavior: Solving the captcha which is displayed in FE will actually solve the captcha and mail is send to configured recepients.

What I tried:
- update powermail to latest available version 10.7.4, does not solve the issue
- downgrade TYPO3 to 11.5.32, this will solve the issue

Only change in TYPO3 11.5.33 I found that might influence the captcha generation and validation processs is:
"2023-11-14 [8fdec56561](https://github.com/typo3/typo3/commit/8fdec56561) [SECURITY] Limit user session to cookie domain"

**Comment by mschwemer** [comment]
Cannot reprodcue it with latest TYPO3 v11 and latest powermail version
