### ISSUE TITLE
Empty 'Used on Page' cell table in Form Overview - TYPO3 BackOffice

### ISSUE THREAD

**Issue by d-haythem** [in2code-de/powermail#947]
Hello, 

Using TYPO3 version 12.4.9, I found this **bug** on powermail extension version 12 where _Used on Page_ not showing the page title ( see screenshot 1 ).
I tracked the error and found that there is a small error in _getPagesWithContentRelatedToForm_ function exactly in the SQL statement ( **list_type** needs to be changed to **ctype** ).

![problem_screenshot](https://github.com/in2code-de/powermail/assets/147941250/1c191202-b921-44bc-9d8e-6e036b29768f)
![problem_srouce](https://github.com/in2code-de/powermail/assets/147941250/f3e654f4-fc6e-4495-8eb2-0910652597d7)

ty!

**Comment by wrock** [comment]
Your solution works!
