### ISSUE TITLE
Fatal Error after upgrade TYPO3 to the version 10.4.10

### ISSUE THREAD

**Issue by vruescas** [in2code-de/powermail#950]
After upgrade TYPO3 to the version 12.4.10 i get the following error message:

Fatal error: Declaration of In2code\Powermail\Condition\PowermailConditionFunctionsProvider::getFunctions() must be compatible with Symfony\Component\ExpressionLanguage\ExpressionFunctionProviderInterface::getFunctions(): array in /var/www/html/vendor/in2code/powermail/Classes/Condition/PowermailConditionFunctionsProvider.php on line 20

**Comment by grischpel** [comment]
I have this after upgrading to version 12.0.3

**Comment by vnc-jboe** [comment]
Downgrade symfony/expression-language to ^6.4 until a fix has been made in powermail

Or patch powermail by replacing in In2code\Powermail\Condition\PowermailConditionFunctionsProvider
line 20: public function getFunctions()

with this:
    public function getFunctions(): array

**Comment by mschwemer** [comment]
Please update to the current powermail version. 

Fixed with 12.1.0 (current version is 12.3.5)
