### ISSUE TITLE
Fatal Error TYPO3 v12.4.10

### ISSUE THREAD

**Issue by MisterMarlu** [in2code-de/powermail#951]
In TYPO3 v12.4.10 they added support for symfony v7, which conflicts with powermail because of one interface:
Symfony\Component\ExpressionLanguage\ExpressionFunctionProviderInterface

This interface is used by In2code\Powermail\Condition\PowermailConditionFunctionsProvider
The method getFunctions() need the declared return type "array"

**Comment by Doc2k** [comment]
Hi,
sry that didn't work for me. 
in PowermailConditionFunctionsProvider.php

```    /**
     * @return array
     */
    public function getFunctions(): array
    {
        return [
            $this->isPowermailPluginOnCurrentPageFunction(),
            $this->isPowermailSubmittedFunction(),
        ];
    }
```

what I've done wrong?

**Comment by MisterMarlu** [comment]
Hi @Doc2k ,
I don't know. To test it I installed powermail v12.0.3 in my TYPO3 v12.4.9 (php 8.2) system.
Then I updated TYPO3 to version 12.4.10 (with the dependencies like symfony) and tried to clear the cache -> the error occurres. The I add the return type to the method, clearing the cache again and everything works fine:

![image](https://github.com/in2code-de/powermail/assets/15226569/bfeff94f-4219-4ed5-8691-254250fcf4bf)

If you was on version 12.4.9 and upgraded to 12.4.10 with the command `composer update typo3/cms-*` it won't update the dependencies of the typo3 packages so symfony would stay in version 6.4 and the return type must not be set.
To update the typo3 packages with the dependencies you have to run `composer update typo3/cms-* -w`.

Could you please tell us what symfony version is installed?

**Comment by Doc2k** [comment]
Hi thanks for your reply,

I dirty fixed the problem by adding` "symfony/expression-language" : "^6.4"` to the main composer.json. so `composer update` keeps  only symfony/expression-language on version 6.4. This line can later be removed when powermail is fixed.

**Comment by KurzGedanke** [comment]
I had the same issue and opend a pull request for it.
https://github.com/in2code-de/powermail/pull/954

**Comment by MisterMarlu** [comment]
@KurzGedanke maybe you should add `"symfony/expression-language": "^v7.0"` to the composer.json file in the pull request too, to be sure that expression-language won't be installed in version 6.4.

**Comment by mschwemer** [comment]
Thanks for your inputs and PR. I will have a look asap. 

It needs more investigation, since powermail should support both symfony versions. 

Related core commit:  https://github.com/TYPO3/typo3/commit/b03970d94dae6865913dbfcdfc25f16b170bdecc

**Comment by MisterMarlu** [comment]
> @KurzGedanke maybe you should add `"symfony/expression-language": "^v7.0"` to the composer.json file in the pull request too, to be sure that expression-language won't be installed in version 6.4.

My bad, of cause you can add a typed return type even if the interface doesn't has a typed return type :facepalm: 
So your PR works with symfony v6.4 and v7.

**Comment by vladimirfalconpiva** [comment]
Wir are having exactly the same issue. With Powermail and 12.4.10 

`Execute typo3 console command
PHP Fatal error:  Declaration of In2code\Powermail\Condition\PowermailConditionFunctionsProvider::getFunctions() must be compatible with Symfony\Component\ExpressionLanguage\ExpressionFunctionProviderInterface::getFunctions(): array in /var/www/html/app/vendor/in2code/powermail/Classes/Condition/PowermailConditionFunctionsProvider.php on line 20

Fatal error: Declaration of In2code\Powermail\Condition\PowermailConditionFunctionsProvider::getFunctions() must be compatible with Symfony\Component\ExpressionLanguage\ExpressionFunctionProviderInterface::getFunctions(): array in /var/www/html/app/vendor/in2code/powermail/Classes/Condition/PowermailConditionFunctionsProvider.php on line 20
Failed to run typo3 database:updateschema -vvv *.add,*.change: exit status 255
`
