### ISSUE TITLE
The Last Version 7.4.3 for Typo3 9.5 is not completly compatible to Typo3 9.5

### ISSUE THREAD

**Issue by hdietrich-timespin** [in2code-de/powermail#955]
I have found old Typoscript-Expressions in the Typoscript! The old Expression will be logged permantly in the log-Files. 

Please change the expressions. 

For example in File /Configuration/TypoScript/Powermail_Frontend/setup.txt: 

chenge the  expression:
`
[globalVar = LIT:0 < {$plugin.tx_powermail.settings.styles.bootstrap.important}]
`
to:

`
[{$plugin.tx_powermail.settings.styles.bootstrap.important}` == 1]
`

Please checkout the attached diff.txt-File for the complete DIFF.

Thank You

[diff.txt](https://github.com/in2code-de/powermail/files/13978579/diff.txt)

**Comment by einpraegsam** [comment]
First of all, there are no update for the very old powermail version.
Next, the version supports TYPO3 8 and 9. The new conditions are not available in 8 - so no failure here.
