### ISSUE TITLE
Repeated Use of "$isSavingOfMailAllowed" Variable in FormController - PHP Warning

### ISSUE THREAD

**Issue by ayesil** [in2code-de/powermail#958]
PHP Warning Message: PHP Warning: Undefined variable $isSavingOfMailAllowed in /var/www/html/vendor/in2code/powermail/Classes/Controller/FormController.php line 268

The potential issue in the provided PHP code is that the variable $isSavingOfMailAllowed might not be defined before it is used in the condition $this->isPersistActive() && $isSavingOfMailAllowed. To address this, I've modified the code to initialize $isSavingOfMailAllowed, initialize before the first conditional block. This ensures that the variable is defined before being used in subsequent conditions:

FormController.php
`
... 
Line 241:

        $event = GeneralUtility::makeInstance(CheckIfMailIsAllowedToSaveEvent::class, $mail);           // <-------- new place
        $this->eventDispatcher->dispatch($event);                                                      // <-------- new place
        $isSavingOfMailAllowed = $event->isSavingOfMailAllowed();                         // <-------- new place
        if ($this->isMailPersistActive($hash)) {
           // >------ Code was here -----------<
            if ($isSavingOfMailAllowed) {
                $this->saveMail($mail);
            }

            $event = GeneralUtility::makeInstance(FormControllerCreateActionAfterMailDbSavedEvent::class, $mail, $this, $hash);
            $this->eventDispatcher->dispatch($event);
            $mail = $event->getMail();
            $hash = $event->getHash();
        }

        if ($this->isNoOptin($mail, $hash)) {
            $this->sendMailPreflight($mail, $hash);
        } else {
            $mailPreflight = GeneralUtility::makeInstance(
                SendOptinConfirmationMailPreflight::class,
                $this->settings,
                $this->conf,
                $this->request
            );
            $mailPreflight->sendOptinConfirmationMail($mail);
            $this->view->assign('optinActive', true);
        }
        if ($this->isPersistActive() && $isSavingOfMailAllowed) { // <----- Problem is here
            $this->mailRepository->update($mail);
            $this->persistenceManager->persistAll();
        }

`

Additional Information:

TYPO3 version: v12
File: Controller/FormController
Testing with D-Optin
Powermail: 12.0.3

Thank You

**Comment by julianhofmann** [comment]
I changed the condition instead of moving the event. The event listeners should only become active if the persistence condition is met. The listeners will always become active if we move the event out of the `if` as suggested.
