### ISSUE TITLE
Client side validation is no more accessible

### ISSUE THREAD

**Issue by phil64** [in2code-de/powermail#962]
This was with parsley.js and version 8.4.

For example: 
- when the focus leaves a required field, a text with an error message is displayed below the field, but a screenreader is not aware of this message.
- when submitting, errors are not reported to the screenreader.

I had to disable client side validation on version 12.0.3.

**Comment by mschwemer** [comment]
We are aware of this issue and it will be definitly be fixed

**Comment by deoostfrees** [comment]
The following improvements were made:

- Add the `aria-invalid' attribute to mark fields as invalid.  0a8fdf6  6d83921
- Add the `aria-live` attribute to let screen readers know when error messages appear.  767d2f5
- Hide the asterisk for required fields with `aria-hidden` for assistive technologies.  9d73016
- Improve form errors (error list at the top of the form through PHP validation)  2bcbc17
  - Use a semantic structure with a heading.
  - Add in-page links to the corresponding form controls.
- Improve the default color contrast for error fields/messages.  ae65e5a

Other improvements will follow as soon as possible in the upcoming major version.
