### ISSUE TITLE
No mail on first submit after clearing TYPO3 cache

### ISSUE THREAD

**Issue by fiedomedia** [in2code-de/powermail#976]
When I clear TYPO3 cache within backend or console the first submit of a powermail form does not send a confirmation mail to the receiver.
I get a success message and the submitted values are stored in the database.
After a page reload or going back to the form and submitting it a second, third, etc. time the mail is sent as usually.

Tested with
- TYPO3 12.4.11
- PHP 8.2
- powermail 12.1.1
- redirect to thank you page is not active but success message

After debugging and digging into the code the bug is caused by this change: https://github.com/in2code-de/powermail/commit/f209418bb00262b8f4b04fd0ec549c71af8b2fe9
When I remove the line the sending of mails works as desired.

**Comment by nilsandresen** [comment]
This is related to this issue https://github.com/in2code-de/powermail/issues/974

**Comment by mschwemer** [comment]
Thanks for your report.

It's fixed in version 12.2.0
