### ISSUE TITLE
Missing TSFE: read property "fe_user" on null

### ISSUE THREAD

**Issue by julianhofmann** [in2code-de/powermail#986]
When submitting a form SessionUtility- methods are called. `ObjectUtility::getTyposcriptFrontendController()` is often called and has return-type `?TypoScriptFrontendController`. However, the nullable case is most often ignored in methods using `getTyposcriptFrontendController()`.

Example:
`SessionUtilitygetSessionValue()` is using TSFE directly, without checking it:
```
$powermailSession = ObjectUtility::getTyposcriptFrontendController()->fe_user->getKey($method, $key);
```
This results in a PHP warning:
```
PHP Warning: Attempt to read property "fe_user" on null in (...)/vendor/in2code/powermail/Classes/Utility/SessionUtility.php line 247
```

Solution
---------

I'm quite not sure what's the better solution: 
* Checking the `null`-return possibility always when using `ObjectUtility::getTyposcriptFrontendController()`
* Change `ObjectUtility::getTyposcriptFrontendController()`, so it would *always* a TSFE-object. If there is none, we could/should fake one (e.g. like EXT:solr/Classes/FrontendEnvironment/Tsfe.php)

**Comment by julianhofmann** [comment]
Warning was displayed to me when - for whatever reason - the TSFE was not present, although it should have been. Clearing the cache solved the specific appearance.

Nevertheless, the code smell remains: we cannot declare `null` as return-type, but then ignore the `null` case in the further code.

**Comment by julianhofmann** [comment]
The error ultimately lay somewhere else: EXT:solr had destroyed the TSFE in combination with a custom PageErrorHandler.
(This is a concise summary).

**Comment by mschwemer** [comment]
So I will close it. Thx.
