### ISSUE TITLE
Unique check failed

### ISSUE THREAD

**Issue by dickymoh** [in2code-de/powermail#989]
Problem or Misunderstanding?
Why does the mail in the attached log fail? All fields are unique.

[log.txt](https://github.com/in2code-de/powermail/files/14522278/log.txt)

Thanks for help.

**Comment by mschwemer** [comment]
Don't know, because the unique check depends on your installation and configuration. 

If you need support for your project, please contact in2code and use the contact form https://www.in2code.de/kontakt/

BTW: you should not make any addresses public  within a log file.
