### ISSUE TITLE
The cObject Viewhelpers not working in  RTE with TYPO3 12.4 

### ISSUE THREAD

**Issue by t3touch** [in2code-de/powermail#990]
If I add an inline VH in an RTE field these error occours:

(1/1) TypeError
TYPO3\CMS\Fluid\ViewHelpers\CObjectViewHelper::getContentObjectRenderer(): Argument #1 ($request) must be of type Psr\Http\Message\ServerRequestInterface, null given, called in /var/www/html/vendor/typo3/cms-fluid/Classes/ViewHelpers/CObjectViewHelper.php on line 130

at TYPO3\CMS\Fluid\ViewHelpers\CObjectViewHelper::renderStatic(array('data' => null, 'typoscriptObjectPath' => 'lib.test', 'currentValueKey' => null, 'table' => ''), object(Closure), object(TYPO3\CMS\Fluid\Core\Rendering\RenderingContext))

**Comment by lisardo2** [comment]
Same problem here: https://stackoverflow.com/questions/78168005/typoscriptobjectpath-throws-error-in-powermail-12
the error is only thrown in the frontend output not in the mail templates. See: https://github.com/in2code-de/powermail/blob/a6e5d927d74ba2454821484b57601958a53cbb72/Classes/Utility/TemplateUtility.php#L98

**Comment by julianhofmann** [comment]
Seems to be caused in TYPO3 v12 by "[Breaking: #98377 - Fluid StandaloneView does not create an Extbase Request anymore](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-98377-FluidStandaloneViewDoesNotCreateAnExtbaseRequestAnymore.html?highlight=standaloneview#custom-standaloneview-code)"

**Comment by adudtkowski** [comment]
I had the same problem when using f:cObject in the RTE for sender mail content (powermail 12.3.1, TYPO3 12.4.14).

This patch helped in my usecase:
[powermail-fix-cObject-viewhelper-in-rte.patch](https://github.com/in2code-de/powermail/files/14978523/powermail-fix-cObject-viewhelper-in-rte.patch)

**Comment by mkoch1707** [comment]
> I had the same problem when using f:cObject in the RTE for sender mail content (powermail 12.3.1, TYPO3 12.4.14).
> 
> This patch helped in my usecase: [powermail-fix-cObject-viewhelper-in-rte.patch](https://github.com/in2code-de/powermail/files/14978523/powermail-fix-cObject-viewhelper-in-rte.patch)

Thanks, this worked also for me.

**Comment by mschwemer** [comment]
Fixed with d9b91b3e671f4826dfa8d2d5e2c170f385987b2b
