### ISSUE TITLE
Integration in Crowdin is uncomplete

### ISSUE THREAD

**Issue by prathers** [in2code-de/powermail#992]
The Crowdin integration for the repository need some attention: https://crowdin.com/project/typo3-extension-powermail/apps/system/github

**Comment by mschwemer** [comment]
Thanks for the hint and taking care of the danish language. 

I would be happy, if you can recheck and give me feedback, if it looks good to you.

**Comment by prathers** [comment]
To me everything looks great - And I'm really sorry for the troubles with the support from Crowdin. To be honest, it's normally very far from there style. My experience is that they answer swift and helpfull - don't know what went wrong.

But good you got it solved - great extension (!!) and good to have it localized. I can see that it is an old translation, so I will go through some labels and tighten up the Danish a bit.

**Comment by mschwemer** [comment]
Thanks for your support!
