### ISSUE TITLE
Optin confirmation fails on powermail 12.1.1

### ISSUE THREAD

**Issue by joergwiedemann** [in2code-de/powermail#995]
Upgrading the system to T3 12 and powermail 12 i tapped in an optin confirmation failure. Everything works fine, but trying to confirm leads to a  working blank page, but nothing happens. After a while it quits with a timeout. The confirmation mail is sent, but not the mail to receiver/admin. Its TYPO3 12, PHP 8.1/8.2 and powermail 12.1.1, after upgrading to 12.2.1 everything works fine. So i think this is the solution.

**Comment by mschwemer** [comment]
Thx for your input. 

As it is no porblem any more., I closed this issue
