### ISSUE TITLE
Missing translation of flexform field settings.flexform.main.formnote

### ISSUE THREAD

**Issue by chrissonntag** [in2code-de/powermail#997]
Powermail-Version: 12.2.1
Typo3-Version: 12.4.12

The flexform field `settings.flexform.main.formnote`, located in `EXT:powermail/Configuration/FlexForms/FlexformPi1.xml` is missing the german translation, when downloading the xliff files from `https://localize.typo3.org/xliff/`.

Could you please adjust the file `de.locallang_db.xlf` anytime soon?
Thx in advance and best
Chris

**Comment by mschwemer** [comment]
I added all missing crowdin translations last month. Geman is at 100% now.
