### ISSUE TITLE
String "Error, no options to show" is not localized

### ISSUE THREAD

**Issue by sypets** [in2code-de/powermail#999]
`powermail/Classes/Domain/Model/Field.php:            $string = 'Error, no options to show';`

This is displayed if a select field is empty:

![image](https://github.com/in2code-de/powermail/assets/13206455/b16a2ba7-7de6-4899-9d88-66eb9880bd12)

Also, IMHO, this should have an empty value (so it is not possible to select this if the field is mandatory, which would make sense).

`powermail/Classes/Domain/Model/Field.php:            $string = $localizedString . '|';`

(in some cases where the fields are populated automatically, the select might be empty)

**Comment by mschwemer** [comment]
Localization added and translated on crowdin two weeks ago.
